server:
  port: 9006
spring:
  application:
    name: mirco-inventory
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/SHOPMANAGER?characterEncoding=UTF8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql
